import './styles/globals.css'
import { Sora } from 'next/font/google'

const sora = Sora({ 
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100','200','300','400','500','600','700','800']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Transition from './components/transition'
import Nav from './components/nav'
import Header from './components/header'
import TopLeftImg from './components/topLeftImg'


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <div className='page bg-site text-white bg-cover bg-no-repeat font-sora relative'>
          
            <TopLeftImg/>
            <Nav/>
            <Header/>
            {children}
          <Transition/>
        </div>
        
      </body>
    </html>
  )
}
